[package]
name = "vbs-enclave"
version = "0.1.0"
edition = "2021"

[lib]
test = false

[dependencies]
thiserror = { version = "2.0", default-features = false }

[dependencies.windows-sys]
version = "0.59.0"
features = [
    "Win32_System_Environment"
]
